[package]
name = "filebin"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", default-features = false, features = ["rt-multi-thread", "macros", "tokio-macros", "net"] }
axum = { version = "0.8.4", default-features = false, features = ["http1", "http2", "json", "query", "tokio"] }
askama = "0.12"
rust-embed = { version = "8.7.2", features = ["axum"] }
mime_guess = "2.0.5"
